Artwork Endpoint
Nookipedia/nookipedia-api pull request #24
Opened 2020-09-26 02:30 UTC by Micalobia

Added the artwork endpoint, as well as support for thumbsize to work on fake_image_url, if it's there.

2020-09-27 04:41 UTC, KevinPayravi requested changes

2020-09-27 04:41 UTC, KevinPayravi commented on app.py
> +
Small lint issue, extra spaces on this new line

2020-09-28 20:06 UTC, Micalobia commented
Okay, so I've done the following:.
- Removed the `image` field from art.
- Added the `_pageName=url` field to art.
- Changed the `fake` field in art to `has_fake`.
- Changed the `?fake=bool` query in the `/nh/art` endpoint to `?hasfake-bool`.
- Renamed the `get_art` and `get_art_all` functions to `get_nh_art` and `get_nh_art_all` to comply with similar functions.
- Fixed the linting issue on line 328.

2020-09-28 20:14 UTC, Micalobia commented
Forgot docs; On that now

2020-09-28 22:07 UTC, Micalobia commented
Should be good to go, long as I didn't miss anything

2020-09-29 04:00 UTC, KevinPayravi approved these changes
LGTM

2020-09-29 04:07 UTC, merged

2020-09-29 04:11 UTC, KevinPayravi commented
Great job setting this up, and thanks for the contribution!